development:
  adapter: postgresql
  database: notes_api_development
  host: localhost
  timeout: 5000
  username: postgres
  password: postgres
test:
  adapter: postgresql
  database: notes_api_test
  host: localhost
  timeout: 5000
  username: postgres
  password: postgres
production:
  adapter: postgresql
  database: notes_api_development
  host: localhost
  timeout: 5000
staging:
  adapter: postgresql
  database: notes_api_development
  host: localhost
  timeout: 5000
